### ISSUE TITLE
Crop Resize

### ISSUE THREAD

**Issue by jamesharding** [mikeboers/Flask-Images#28]
More of a feature request than an issue:

If an uploaded image is 200x400px, and in crop mode the desired output is 400px by 400px, would it be possible to allow the outputted image to be a zoomed/enlarged cropped image that is 400x400px and zoomed on the centre of the image? Right now, the output will never be larger than the original (and would output an image of the original 200x400 size in the above example).

**Comment by mikeboers** [comment]
I faced the same issue recently on my own photo site during the transition to HiDPI images. As of v2.1.0, cropped images should be enlarged unless you pass `enlarge=False` (see [example from my site](https://github.com/mikeboers/mikeboers.com/blob/master/templates/photos/photo.haml#L45-L55)).

Let me know if the latest version is[n't] working for you.

**Comment by jamesharding** [comment]
On your site, that is in fit mode as opposed to the crop mode. With fit, the aspect ratio of the original image is unchanged, but I guess that what I am looking for is for image to be scaled up to have its shortest edges > the required size, and then for the crop to happen. In my case I want all outputs to be perfect squares), and for them to all be the exact size that is passed to the function.

I am using 'resized_img_src(user.photo_path, width=400, height=400, mode='fit', quality=95)' as my call.
If the pictures have both edges longer than 400px it works perfectly. If one edge is less than 400px, then the output image no longer has a square aspect ratio.

**Comment by mikeboers** [comment]
There is also [this example](https://github.com/mikeboers/mikeboers.com/blob/master/templates/photos/album.haml#L147-L157), in which I am enlarging a crop because I too want perfect squares (or rectangles; [here it is in action](http://mikeboers.com/photos/2014-selects)).

I could be wrong and mine working due to the HiDPI-ness. Can you confirm for me you are on v2.1.0, or the master from GitHub?

**Comment by jamesharding** [comment]
I am on the PIP version 2.1.1.
With the version on your site, if you passed it an image that was smaller than the desired output, does is still correctly scale it up and maintain the output size/aspect ratio?

![screenshot 2015-01-07 21 28 15](https://cloud.githubusercontent.com/assets/1170231/5652774/37eb0394-96b4-11e4-95dd-88534b66ab04.png)

![screenshot 2015-01-07 21 30 52](https://cloud.githubusercontent.com/assets/1170231/5652807/a1ac583c-96b4-11e4-863e-3ead8872f012.png)

Here is what it looks like, with Tom's picture being 265x361 input, and the output is also 265x361.

**Comment by mikeboers** [comment]
I think it is actually an issue with caching. Stay tuned.

**Comment by mikeboers** [comment]
I think it was a caching issue (in which the enlarge parameter wasn't being taken into account when caching the results, so if you added `enlarge=True` without changing anything else then it wouldn't even try to resize the image).

Please try the new master. I've also tried to document a few more parameters. ;)

**Comment by jamesharding** [comment]
Hmmm, it still seems to be an issue even with the latest master. Have you tried testing it on your site with an image that is smaller than the output resolution (and not of the same aspect ratio too)?

**Comment by mikeboers** [comment]
Yup. [The demo works as expected too](https://flask-images.herokuapp.com/?url=https%3A%2F%2Ffarm9.staticflickr.com%2F8121%2F8612879173_72401681d2_m_d.jpg&transform=&width=400&height=400&background=%23000000&enlarge=on) (the source is 240x160).

**Comment by jamesharding** [comment]
Brilliant, that has fixed it :)

Thank-you! This plugin is fantastic.

**Comment by mikeboers** [comment]
Awesome! You should see the problems I have when I keep introducing this same caching bug over and over...

I'll let it settle, and then release on the PyPI.

**Comment by mikeboers** [comment]
I have now released this on the PyPI as v2.1.2. =]
