### ISSUE TITLE
fail to load url

### ISSUE THREAD

**Issue by veasna234** [mikeboers/Flask-Images#33]
Hi, I am new to flask, and i want to use flask image to resize my image, i have follow all the step.
but i have problem with  IMAGES_URL i use the default one (imgsizer).   when i run my web app, i can not get the resize image. i use firebug to check it said fail to load url.
Please help me , what i am doing wrong?

**Comment by iurisilvio** [comment]
Can you show us an error? Put your app in debug mode to get a better error message.
