### ISSUE TITLE
flask-images endpoint with Flask-Restful

### ISSUE THREAD

**Issue by erwinyusrizal** [mikeboers/Flask-Images#46]
Hi @mikeboers ,

Any idea to make this extension work with flask-restful?

Cheers,

**Comment by erwinyusrizal** [comment]
OMG...My mistake

**Comment by erwinyusrizal** [comment]
Sorry I have to reopen this, I was spoke too soon before. It works for static but not the flask-restful endpoint, it returns 404, any idea how to fix this?

Thank you

**Comment by wzuo** [comment]
You can use function to return image source, then use this as a field value for flask restful. I think this is proper way to serve images via REST, not embedding in JSON

**Comment by erwinyusrizal** [comment]
Yes I got it working now, I forgot I override all the response to json
