### ISSUE TITLE
Change the constant_time_compare import from itsdangerous lib

### ISSUE THREAD

**Issue by Riverfount** [mikeboers/Flask-Images#49]

**Comment by mikeboers** [comment]
Change it how, and why?

**Comment by Riverfount** [comment]
I use this library in my projects, and today show me an error to import this constant. And, I investigate and discover that there is a change in the location of the constant in the itsdangerous lib. I create this issue and I will submit a PR to correct it. Of course, if you approve this ok! if not, ok too!
