### ISSUE TITLE
The generated link contains quotes

### ISSUE THREAD

**Issue by ovionlogis** [mikeboers/Flask-Images#51]
Faced the problem that the link to the image contains quotes:

>/imgsizer/image.jpg?v=WzdUWw&w=480&s=**b'PKgfqQAtQuvQseN6-gErB3tRjtM'**

The whole problem in the `s` parameter, looks like the bytes are converted incorrectly into a string.

Python 3.7
Flask-Images 3.0.1
Linux Mint 19

**Comment by mikeboers** [comment]
Amazing. Those are some quality tests I've written here. 🙄

**Comment by ovionlogis** [comment]
@mikeboers I do not understand what you mean, can you explain?

**Comment by jllopezpino** [comment]
Same problem here... Did you find any workaround @ovionlogis ?

We tried to use `replace("'", '%27')`, but errors keep coming.
Example:

`        <img src="{{ url_for('images', format=session.get('image_format'), filename='image.png', width=550, quality=75).replace("'", '%27') }}"
`

**Comment by ovionlogis** [comment]
@jllopezpino fork and decode **utf-8**

[https://github.com/mikeboers/Flask-Images/compare/master...ovionlogis:master](https://github.com/mikeboers/Flask-Images/compare/master...ovionlogis:master)

**Comment by mikeboers** [comment]
I just pulled @ovionlogis changes. Thanks!
